/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["byId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Constraints: {
            makes?: string[];
            bodyTypes?: ("HATCHBACK" | "SEDAN" | "COMPACT_SUV" | "SUV" | "MPV" | "LUXURY")[];
            fuelTypes?: ("PETROL" | "DIESEL" | "CNG" | "ELECTRIC" | "HYBRID")[];
            transmissions?: ("MANUAL" | "AMT" | "CVT" | "DCT" | "TORQUE_CONVERTER")[];
            cities?: string[];
            priceInr?: components["schemas"]["NumRange"];
            emiMonthly?: components["schemas"]["NumRange"];
            kmDriven?: components["schemas"]["NumRange"];
            year?: components["schemas"]["NumRange"];
            seats?: components["schemas"]["NumRange"];
            /** Format: int64 */
            maxOwners?: number;
            /** Format: int64 */
            minNcapStars?: number;
        };
        FilterSpec: {
            constraints?: components["schemas"]["Constraints"];
            preferences?: components["schemas"]["Preference"][];
            freeText?: string;
            /** @enum {string} */
            sort?: "RELEVANCE" | "PRICE_ASC" | "PRICE_DESC" | "KM_ASC" | "YEAR_DESC" | "NEWEST_LISTED";
            appliedConcepts?: string[];
            unmapped?: string[];
        };
        NumRange: {
            /** Format: int64 */
            gte?: number;
            /** Format: int64 */
            lte?: number;
        };
        Preference: {
            /** @enum {string} */
            field: "SEATS" | "NCAP_STARS" | "BOOT_LITRES" | "MILEAGE_KMPL" | "PRICE_INR" | "KM_DRIVEN" | "YEAR" | "ENGINE_CC" | "INSPECTION_SCORE" | "OWNERS";
            /** @enum {string} */
            op: "GTE" | "LTE" | "EQ";
            /** Format: double */
            value: number;
            /** Format: double */
            boost?: number;
            source?: string;
        };
        SearchRequest: {
            query?: string;
            filters?: components["schemas"]["FilterSpec"];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
        };
        Chip: {
            kind?: string;
            field?: string;
            label?: string;
            source?: string;
        };
        Interpretation: {
            chips?: components["schemas"]["Chip"][];
            notes?: string[];
        };
        SearchResponse: {
            interpretation?: components["schemas"]["Interpretation"];
            filters?: components["schemas"]["FilterSpec"];
            results?: components["schemas"]["Vehicle"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            facets?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            parser?: string;
            /** Format: int64 */
            tookMs?: number;
            warnings?: string[];
            scoreSql?: string;
        };
        Vehicle: {
            /** Format: int64 */
            id?: number;
            registration?: string;
            make?: string;
            model?: string;
            variant?: string;
            /** Format: int32 */
            year?: number;
            /** @enum {string} */
            bodyType?: "HATCHBACK" | "SEDAN" | "COMPACT_SUV" | "SUV" | "MPV" | "LUXURY";
            /** @enum {string} */
            fuelType?: "PETROL" | "DIESEL" | "CNG" | "ELECTRIC" | "HYBRID";
            /** @enum {string} */
            transmission?: "MANUAL" | "AMT" | "CVT" | "DCT" | "TORQUE_CONVERTER";
            /** Format: int64 */
            priceInr?: number;
            /** Format: int32 */
            emiMonthly?: number;
            /** Format: int32 */
            kmDriven?: number;
            /** Format: int32 */
            owners?: number;
            /** Format: int32 */
            seats?: number;
            /** Format: int32 */
            engineCc?: number;
            mileageKmpl?: number;
            /** Format: int32 */
            rangeKm?: number;
            /** Format: int32 */
            bootLitres?: number;
            /** Format: int32 */
            ncapStars?: number;
            city?: string;
            hub?: string;
            colour?: string;
            /** @enum {string} */
            status?: "AVAILABLE" | "RESERVED" | "SOLD";
            /** Format: date */
            listedAt?: string;
            inspectionScore?: number;
            dealScore?: number;
            features?: string[];
            /** Format: double */
            score?: number;
        };
        ConceptInfo: {
            key?: string;
            label?: string;
            kind?: string;
            terms?: string[];
        };
        Range: {
            /** Format: int64 */
            min?: number;
            /** Format: int64 */
            max?: number;
        };
        SchemaResponse: {
            enums?: {
                [key: string]: string[];
            };
            concepts?: components["schemas"]["ConceptInfo"][];
            ranges?: {
                [key: string]: components["schemas"]["Range"];
            };
            cities?: string[];
            makes?: string[];
            sorts?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    byId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Vehicle"];
                };
            };
        };
    };
    schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SchemaResponse"];
                };
            };
        };
    };
}
