/**
 * Types derived from the backend's own OpenAPI document, generated by
 * `npm run types` from springdoc's /v3/api-docs. Rename a field in a Java
 * record and this file changes under you, so the contract cannot silently
 * drift — the build breaks at the call site instead of a user seeing undefined.
 */
import type { components } from './api-types'

export type FilterSpec     = components['schemas']['FilterSpec']
export type Constraints    = components['schemas']['Constraints']
export type NumRange       = components['schemas']['NumRange']
export type Preference     = components['schemas']['Preference']
export type Vehicle        = components['schemas']['Vehicle']
export type SearchResponse = components['schemas']['SearchResponse']

/**
 * springdoc marks every record component optional, because a Java record
 * carries no nullability metadata and springdoc 3.1 does not read the JSpecify
 * annotations Spring itself uses. Rather than sprinkle `?.` through every
 * component, the server's actual guarantees are asserted once, at the single
 * point where a response enters the app.
 *
 * The right long-term fix is on the backend — `@Schema(requiredMode = REQUIRED)`
 * on the response records, so the generator emits these as required and this
 * block disappears.
 */
export type Chip = {
  kind: 'CONSTRAINT' | 'PREFERENCE'
  field: string
  label: string
  source?: string
}

export type SearchResult = {
  interpretation: { chips: Chip[]; notes: string[] }
  filters: FilterSpec
  results: Vehicle[]
  totalElements: number
  page: number
  size: number
  facets: Record<string, Record<string, number>>
  parser: string
  tookMs: number
  warnings: string[]
  scoreSql?: string
}
